# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\GIX\MOL\rpcserver_tools\frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(543, 363)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_device_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_device_button.setGeometry(QtCore.QRect(84, 140, 81, 23))
        self.add_device_button.setObjectName("add_device_button")
        self.start_record_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_record_button.setGeometry(QtCore.QRect(84, 180, 81, 23))
        self.start_record_button.setObjectName("start_record_button")
        self.time_stamp_button = QtWidgets.QPushButton(self.centralwidget)
        self.time_stamp_button.setGeometry(QtCore.QRect(84, 220, 81, 23))
        self.time_stamp_button.setObjectName("time_stamp_button")
        self.list_dev_button = QtWidgets.QPushButton(self.centralwidget)
        self.list_dev_button.setGeometry(QtCore.QRect(84, 260, 81, 23))
        self.list_dev_button.setObjectName("list_dev_button")
        self.device_ip = QtWidgets.QLineEdit(self.centralwidget)
        self.device_ip.setGeometry(QtCore.QRect(210, 140, 113, 20))
        self.device_ip.setObjectName("device_ip")
        self.device_id = QtWidgets.QLineEdit(self.centralwidget)
        self.device_id.setGeometry(QtCore.QRect(350, 140, 113, 20))
        self.device_id.setObjectName("device_id")
        self.end_rec_button = QtWidgets.QPushButton(self.centralwidget)
        self.end_rec_button.setGeometry(QtCore.QRect(210, 180, 101, 23))
        self.end_rec_button.setObjectName("end_rec_button")
        self.retrieve_button = QtWidgets.QPushButton(self.centralwidget)
        self.retrieve_button.setGeometry(QtCore.QRect(210, 220, 101, 23))
        self.retrieve_button.setObjectName("retrieve_button")
        self.experiment_name = QtWidgets.QLineEdit(self.centralwidget)
        self.experiment_name.setGeometry(QtCore.QRect(350, 180, 113, 20))
        self.experiment_name.setObjectName("experiment_name")
        self.reboot_button = QtWidgets.QPushButton(self.centralwidget)
        self.reboot_button.setGeometry(QtCore.QRect(214, 260, 91, 23))
        self.reboot_button.setObjectName("reboot_button")
        self.duration = QtWidgets.QLineEdit(self.centralwidget)
        self.duration.setGeometry(QtCore.QRect(340, 220, 141, 20))
        self.duration.setObjectName("duration")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 543, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_device_button.setText(_translate("MainWindow", "Add device"))
        self.start_record_button.setText(_translate("MainWindow", "Start record"))
        self.time_stamp_button.setText(_translate("MainWindow", "Time stamp"))
        self.list_dev_button.setText(_translate("MainWindow", "List dev"))
        self.device_ip.setText(_translate("MainWindow", "device ip"))
        self.device_id.setText(_translate("MainWindow", "device id"))
        self.end_rec_button.setText(_translate("MainWindow", "End recording"))
        self.retrieve_button.setText(_translate("MainWindow", "Retrieve"))
        self.experiment_name.setText(_translate("MainWindow", "Experiment name"))
        self.reboot_button.setText(_translate("MainWindow", "Reboot"))
        self.duration.setText(_translate("MainWindow", "Experiment duration(s)"))
